# Generated by Django 2.2.1 on 2019-05-25 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='项目名称')),
                ('env', models.IntegerField(choices=[(1, 'dev'), (2, 'docker-dev'), (3, 'docker-hotfix'), (4, 'stress')], default=1, verbose_name='项目环境')),
                ('type', models.IntegerField(choices=[(1, '教师空间'), (2, '学生pad'), (3, '教师pad'), (4, '商城'), (5, 'OKAY+')], default=1, verbose_name='项目类型')),
                ('desc', models.CharField(blank=True, max_length=200, verbose_name='项目描述')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='项目创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='项目更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'entity_project',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='脚本名称')),
                ('pre_number', models.IntegerField(verbose_name='并发数')),
                ('pre_time', models.IntegerField(verbose_name='压测时长')),
                ('url', models.CharField(max_length=200, verbose_name='压测url')),
                ('time_out', models.IntegerField(blank=True, default=5000, verbose_name='超时时间')),
                ('request_type', models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'DELETE')], default=1, verbose_name='接口请求类型')),
                ('protocol', models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'DELETE')], default=1, verbose_name='接口协议')),
                ('ins', models.CharField(blank=True, max_length=100, verbose_name='dubbo接口名称')),
                ('assert_text', models.CharField(blank=True, max_length=50, verbose_name='响应断言文本')),
                ('method', models.CharField(blank=True, max_length=30, verbose_name='dubbo接口方法名')),
                ('params', models.CharField(blank=True, max_length=200, verbose_name='压测接口参数值')),
                ('param_type', models.CharField(blank=True, max_length=100, verbose_name='dubbo接口请求参数类型')),
                ('cookie', models.CharField(blank=True, max_length=300, verbose_name='cookie')),
                ('header', models.CharField(blank=True, max_length=300, verbose_name='header')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'verbose_name': '脚本',
                'db_table': 'entity_script',
            },
        ),
    ]
