# Generated by Django 2.2.1 on 2019-05-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='version',
            field=models.CharField(blank=True, max_length=10, verbose_name='接口版本'),
        ),
        migrations.AlterField(
            model_name='script',
            name='protocol',
            field=models.IntegerField(choices=[(1, 'http'), (2, 'dubbo'), (3, 'socket')], default=1, verbose_name='接口协议'),
        ),
    ]
