# Generated by Django 2.2.1 on 2019-05-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190525_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='request_type',
            field=models.IntegerField(blank=True, choices=[(1, 'GET'), (2, 'POST'), (3, 'DELETE')], verbose_name='接口请求类型'),
        ),
        migrations.AlterField(
            model_name='script',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='压测url'),
        ),
    ]
