# Generated by Django 2.2.1 on 2019-05-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='ip',
            field=models.CharField(blank=True, default='localhost', max_length=10, verbose_name='服务器ip'),
        ),
        migrations.AddField(
            model_name='script',
            name='port',
            field=models.IntegerField(blank=True, default=4444, verbose_name='接口版本'),
        ),
    ]
