# Generated by Django 2.2.1 on 2019-06-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190530_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='method',
            field=models.CharField(blank=True, max_length=80, verbose_name='dubbo接口方法名'),
        ),
        migrations.AlterField(
            model_name='script',
            name='request_type',
            field=models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'DELETE')], default=1, verbose_name='接口请求类型'),
        ),
    ]
