# Generated by Django 2.2.1 on 2019-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190612_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='params',
            field=models.CharField(blank=True, max_length=600, verbose_name='压测接口参数值'),
        ),
    ]
