# Generated by Django 2.2.1 on 2019-06-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190612_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='cookie',
            field=models.TextField(blank=True, max_length=3000, verbose_name='cookie'),
        ),
        migrations.AlterField(
            model_name='script',
            name='header',
            field=models.TextField(blank=True, max_length=3000, verbose_name='header'),
        ),
    ]
